//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by snowss.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SNOWSS_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDB_SHOW                        129
#define IDB_CONDOM1                     2000
#define IDB_CONDOM2                     131
#define IDB_CONDOM3                     132
#define IDB_CONDOM4                     133
#define IDB_CONDOM5                     134
#define IDB_CONDOM6                     135
#define IDB_CONDOM7                     136
#define IDB_CONDOM8                     137
#define IDB_PINK_CONDOM1                140
#define IDB_PINK_CONDOM2                141
#define IDB_PINK_CONDOM3                142
#define IDB_PINK_CONDOM4                143
#define IDB_PINK_CONDOM5                144
#define IDB_PINK_CONDOM6                145
#define IDB_PINK_CONDOM7                146
#define IDB_PINK_CONDOM8                147
#define IDB_REVERSE_CONDOM1             149
#define IDB_FREE_LOGO                   150
#define IDB_REVERSE_CONDOM2             151
#define IDB_REVERSE_CONDOM3             152
#define IDB_REVERSE_CONDOM4             153
#define IDB_REVERSE_CONDOM5             154
#define IDB_REVERSE_CONDOM6             155
#define IDB_REVERSE_CONDOM7             156
#define IDB_REVERSE_CONDOM8             157
#define IDB_UNDICHT_CONDOM1             158
#define IDB_UNDICHT_CONDOM2             159
#define IDB_UNDICHT_CONDOM3             160
#define IDB_UNDICHT_CONDOM4             161
#define IDB_UNDICHT_CONDOM5             162
#define IDB_UNDICHT_CONDOM6             163
#define IDB_UNDICHT_CONDOM7             164
#define IDB_UNDICHT_CONDOM8             165
#define IDB_ROTATE_CONDOM1              166
#define IDB_ROTATE_CONDOM2              167
#define IDB_ROTATE_CONDOM3              168
#define IDB_ROTATE_CONDOM4              169
#define IDB_ROTATE_CONDOM5              170
#define IDB_ROTATE_CONDOM6              171
#define IDB_ROTATE_CONDOM7              172
#define IDB_ROTATE_CONDOM8              173
#define IDB_BIG_CONDOM1                 174
#define IDB_BIG_CONDOM2                 175
#define IDB_BIG_CONDOM3                 176
#define IDB_BIG_CONDOM4                 177
#define IDB_BIG_CONDOM5                 178
#define IDB_BIG_CONDOM6                 179
#define IDB_BIG_CONDOM7                 180
#define IDB_BIG_CONDOM8                 181
#define IDB_RAKETE_CONDOM1              182
#define IDB_RAKETE_CONDOM2              183
#define IDB_RAKETE_CONDOM3              184
#define IDB_RAKETE_CONDOM4              185
#define IDB_RAKETE_CONDOM5              186
#define IDB_RAKETE_CONDOM6              187
#define IDB_RAKETE_CONDOM7              188
#define IDB_RAKETE_CONDOM8              189
#define IDB_SPERM1                      190
#define IDB_SPERM2                      191
#define IDB_SPERM3                      192
#define IDB_SPERM4                      193
#define IDB_SPERM5                      194
#define IDB_SPERM6                      195
#define IDB_SPERM7                      196
#define IDB_SPERM8                      197
#define IDB_EARTH01                     198
#define IDB_EARTH02                     199
#define IDB_EARTH03                     200
#define IDB_EARTH04                     201
#define IDB_EARTH05                     202
#define IDB_EARTH06                     203
#define IDB_EARTH07                     204
#define IDB_EARTH08                     205
#define IDB_EARTH09                     206
#define IDB_EARTH10                     207
#define IDB_EARTH11                     208
#define IDB_EARTH12                     209
#define IDB_EARTH13                     210
#define IDB_EARTH14                     211
#define IDB_EARTH15                     212
#define IDB_EARTH16                     213
#define IDB_EARTH17                     214
#define IDB_EARTH18                     215
#define IDB_EARTH19                     216
#define IDB_EARTH20                     217
#define IDB_EARTH21                     218
#define IDB_EARTH22                     219
#define IDB_EARTH23                     220
#define IDB_EARTH24                     221
#define IDB_EARTH25                     222
#define IDB_EARTH26                     223
#define IDB_EARTH27                     224
#define IDB_EARTH28                     225
#define IDB_EARTH29                     226
#define IDB_EARTH30                     227
#define IDB_EARTH31                     228
#define IDB_EARTH32                     229
#define IDB_EARTH33                     230
#define IDB_EARTH34                     231
#define IDB_EARTH35                     232
#define IDB_EARTH36                     233
#define IDB_FADENKREUZ                  234
#define IDB_BITMAP1                     235
#define IDB_EX_CONDOM08                 236
#define IDB_EX_CONDOM02                 237
#define IDB_EX_CONDOM03                 238
#define IDB_EX_CONDOM04                 239
#define IDB_EX_CONDOM05                 240
#define IDB_EX_CONDOM06                 241
#define IDB_EX_CONDOM07                 242
#define IDB_EX_CONDOM01                 243
#define IDB_EX_CONDOM16                 244
#define IDB_EX_CONDOM10                 245
#define IDB_EX_CONDOM11                 246
#define IDB_EX_CONDOM12                 247
#define IDB_EX_CONDOM13                 248
#define IDB_EX_CONDOM14                 249
#define IDB_EX_CONDOM15                 250
#define IDB_EX_CONDOM09                 251
#define IDC_RA_DOT                      1000
#define IDC_RA_SQUARE                   1001
#define IDC_RA_RAND                     1002
#define IDC_SLI_WIDTH                   1003
#define IDC_SLI_SPEED                   1004
#define IDC_DEF                         1005
#define IDC_RA_CIRCLE                   1007
#define IDC_COUNT_EDIT                  1010
#define IDC_COUNT_SPIN                  1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        252
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
